---
  - name: Set work dir
    set_fact:
      workdir: "/tmp/amtls_{{ ansible_hostname }}"
    changed_when: False

  - name: Ensure work dir exists
    file:
      dest: "{{ workdir }}"
      state: directory
    changed_when: False
    delegate_to: localhost
    check_mode: False

  - name: Copy DH parameters to server
    become: True
    copy:
      src: "ffdhe2048.pem"
      dest: "/etc/postfix/dh-2048.pem"
      owner: root
      group: postfix
      mode: 0640

  - name: Check if SSL certificate exists
    become: True
    stat: path=/etc/postfix/server.pem
    register: certstat
    changed_when: False

  - name: Copy dummy certificate
    become: True
    copy: src={{ item.key }} dest=/etc/postfix/{{ item.value }} owner=postfix group=root mode=0660
    when: not certstat.stat.exists
    with_dict:
      "dummycert.pem": "server.pem"
      "dummykey.pem": "server.key"

  - name: Extract live certificate
    become: True
    when: mailserver_have_cert|bool
    copy:
      content: "{{ mailserver_tls_cert }}"
      dest: "/etc/postfix/server.pem"
      owner: postfix
      group: postfix
      mode: 0660

  - name: Extract live certificate key
    become: True
    when: mailserver_have_cert|bool
    copy:
      content: "{{ mailserver_tls_key }}"
      dest: "/etc/postfix/server.key"
      owner: postfix
      group: postfix
      mode: 0660

  - name: Check if SSL client certificate exists
    become: True
    stat: path=/etc/postfix/client.pem
    register: ccertstat
    changed_when: False

  - name: Generate self-signed client certificate
    command: openssl req -x509 -sha384 -newkey rsa:4096 -keyout {{ workdir }}/{{ansible_hostname}}.key -out {{ workdir }}/{{ansible_hostname}}.pem -days 3650 -config {{ role_path }}/files/clientcert.cnf -nodes -subj '/CN={{ansible_fqdn}}'
    delegate_to: localhost
    check_mode: False
    when: not ccertstat.stat.exists

  - name: Copy client certificate
    become: True
    copy:
      src: "{{ workdir }}/{{ ansible_hostname }}.{{ item }}"
      dest: "/etc/postfix/{{ ansible_hostname}}.{{ item }}"
      owner: postfix
      group: root
      mode: 0660
    when: not ccertstat.stat.exists
    with_items:
      - 'key'
      - 'pem'

  - name: Cleanup
    file:
      dest: "{{ workdir }}"
      state: absent
    changed_when: False
    delegate_to: localhost
