---
  - name: restart postfix
    become: True
    service: name=postfix enabled=yes state=restarted
    
  - name: restart dovecot
    become: True
    service: name=dovecot enabled=yes state=restarted
  
  - name: restart opendkim
    become: True
    service: name=opendkim enabled=yes state=restarted

  - name: reload systemd-dovecot
    become: True
    command: systemctl daemon-reload
    notify: restart dovecot

  - name: reload systemd-ldap
    become: True
    command: systemctl daemon-reload
    notify: restart ldap-groups

  - name: restart ldap-groups
    become: True
    service: name=ldap-groups-sync.timer enabled=yes state=restarted
